apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: insight-admin-portal
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  ENVIRONMENT: {{ .Values.backend.env.ENVIRONMENT | quote }}
  LOG_LEVEL: {{ .Values.backend.env.LOG_LEVEL | quote }}
