metadata name = 'insight per-app infrastructure'
metadata description = 'Full Azure footprint for the insight admin-portal app: Key Vault (+CMK keys), Postgres (insight+spicedb), Redis, Service Bus, Storage, AI Search, 3 Cognitive accounts, App Configuration, a shared workload identity federated to 8 ServiceAccounts, private endpoints and data-plane role assignments. Ported from infra/tenant/app/insight (Terraform). Outputs the non-secret appInfra map the insight Helm chart consumes.'

targetScope = 'resourceGroup'

// ─── Wiring (supplied by the provisioning platform / root) ────────────────────
@description('ApplicationDeployment applicationId this module satisfies.')
param applicationId string = 'insight'

@description('Unique tenant identifier.')
param tenantName string

@description('Environment name (dev, qa, uat). Used as a name suffix and App Config key label.')
param env string

@description('Azure region for all resources.')
param location string = resourceGroup().location

@description('Kubernetes namespace where the tenant workloads / ServiceAccounts live.')
param tenantNamespace string

@description('AKS cluster OIDC issuer URL (issuer of the federated identity credentials).')
param aksOidcIssuerUrl string

@description('Resource ID of the shared private-endpoint subnet.')
param peSubnetId string

@description('Tenant workspace subdomain used to build public URLs.')
param workspaceSubdomain string

@description('Tenant routing domain used to build public URLs.')
param routingDomain string

@description('Tags merged onto every resource.')
param commonTags object = {}

// ─── Private DNS zone IDs (resolved by the platform in the connectivity sub) ──

// ─── Platform ACS email (optional) ────────────────────────────────────────────
@description('ACS SDK endpoint for insight email send (projected into appInfra/App Config).')
param platformAcsEndpoint string = ''
@description('Platform sender From address (projected into appInfra/App Config).')
param platformAcsFromEmail string = ''
@description('Name of the platform ACS Communication Service (enables the email-sender role grant when set with platformAcsResourceGroup).')
param platformAcsName string = ''
@description('Resource group of the platform ACS Communication Service.')
param platformAcsResourceGroup string = ''

// ─── Sizing (defaults match the validated Terraform) ──────────────────────────
@description('Key Vault SKU.')
param keyVaultSku string = 'premium'
@description('PostgreSQL major version.')
param postgresVersion string = '16'
@description('PostgreSQL Flexible Server SKU.')
param postgresSkuName string = 'GP_Standard_D4ds_v5'
@description('PostgreSQL storage in MB.')
param postgresStorageMb int = 131072
@description('PostgreSQL backup retention (7-35 days).')
@minValue(7)
@maxValue(35)
param postgresBackupRetentionDays int = 14
@description('PostgreSQL geo-redundant backup.')
param postgresGeoRedundantBackup bool = true
@description('Redis capacity.')
param redisCapacity int = 1
@description('Redis family.')
param redisFamily string = 'P'
@description('Redis SKU.')
param redisSkuName string = 'Premium'
@description('Service Bus Premium messaging units.')
param servicebusCapacity int = 1
@description('AI Search SKU.')
param searchSku string = 'standard'
@description('AI Search replicas.')
param searchReplicaCount int = 2
@description('AI Search partitions.')
param searchPartitionCount int = 1
@description('Storage SKU.')
param storageSku string = 'Standard_ZRS'
@description('App Configuration SKU.')
param appConfigurationSku string = 'standard'
@description('SKU for Speech and Document Intelligence.')
param cognitiveServicesSku string = 'S0'
@description('SKU for the Translator account.')
param translatorSku string = 'S1'
@description('Optional blob lifecycle delete threshold in days (0 disables).')
param storageLifecycleDeleteAfterDays int = 0

// ─── Secrets (generated by the platform, never emitted as outputs) ────────────

// ─── Naming ───────────────────────────────────────────────────────────────────
// Bicep has no sha1; use uniqueString (deterministic, lowercase alphanumeric).
@description('Resource group holding the private DNS zones. Pass {{dnsZoneResourceGroup}} — the footprint creates one zone per service type and links them to the cluster vnet.')
param dnsZoneResourceGroup string

@description('The tenant\'s own Key Vault, holding the credentials this deployment needs. Pass {{vaultName}}.')
param vaultName string

@description('Resource group of that vault. Pass {{vaultResourceGroup}}.')
param vaultResourceGroup string

@description('Secret store id whose keys hold the insight credentials. The vault secret names are set-<id>--<key>.')
param secretSetId string = 'insight-secrets'

// Zone ids are derived rather than passed: the names are fixed by Azure (a
// private endpoint's DNS zone group only works against these exact names), so
// eight parameters would be eight chances to get one wrong.

// Fixed by Azure — a private endpoint's DNS zone group only resolves against
// these exact zone names.
var kvDnsZoneId = resourceId(subscription().subscriptionId, dnsZoneResourceGroup, 'Microsoft.Network/privateDnsZones', 'privatelink.vaultcore.azure.net')
var blobDnsZoneId = resourceId(subscription().subscriptionId, dnsZoneResourceGroup, 'Microsoft.Network/privateDnsZones', 'privatelink.blob.${environment().suffixes.storage}')
var cognitiveDnsZoneId = resourceId(subscription().subscriptionId, dnsZoneResourceGroup, 'Microsoft.Network/privateDnsZones', 'privatelink.cognitiveservices.azure.com')
var appConfigurationDnsZoneId = resourceId(subscription().subscriptionId, dnsZoneResourceGroup, 'Microsoft.Network/privateDnsZones', 'privatelink.azconfig.io')
var postgresDnsZoneId = resourceId(subscription().subscriptionId, dnsZoneResourceGroup, 'Microsoft.Network/privateDnsZones', 'privatelink.postgres.database.azure.com')
var redisDnsZoneId = resourceId(subscription().subscriptionId, dnsZoneResourceGroup, 'Microsoft.Network/privateDnsZones', 'privatelink.redis.cache.windows.net')
var searchDnsZoneId = resourceId(subscription().subscriptionId, dnsZoneResourceGroup, 'Microsoft.Network/privateDnsZones', 'privatelink.search.windows.net')
var servicebusDnsZoneId = resourceId(subscription().subscriptionId, dnsZoneResourceGroup, 'Microsoft.Network/privateDnsZones', 'privatelink.servicebus.windows.net')

resource tenantVault 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
  name: vaultName
  scope: resourceGroup(vaultResourceGroup)
}

var nameHash = substring(uniqueString(subscription().subscriptionId, tenantName, applicationId), 0, 12)
var nameSuffix = '${nameHash}-${env}'

var tags = union(commonTags, {
  application_id: applicationId
  layer: 'tenant-app'
})

var administratorLogin = 'pgadmin'
var postgresDatabases = [ 'insight', 'spicedb' ]
var servicebusQueues = [ 'meeting-queue', 'insight-indexer-queue' ]
var storageContainers = [ 'insight-user-documents', 'insight-audio-brief' ]

var workloadServiceAccounts = [
  'backend-sa'
  'bff-sa'
  'appconfig-provider-sa'
  'agentic-core-sa'
  'llm-gateway-sa'
  'digital-simulator-sa'
  'decision-register-sa'
  'translation-sa'
]

// Names
var kvName = 'kv-${nameSuffix}'
var postgresName = 'psql-${nameSuffix}'
var redisName = 'redis-${nameSuffix}'
var servicebusName = 'sb-${nameSuffix}'
var searchName = 'srch-${nameSuffix}'
var appconfigName = 'appcs-${nameSuffix}'
var speechName = 'spch-${nameSuffix}'
var translatorName = 'trnsl-${nameSuffix}'
var documentIntelligenceName = 'di-${nameSuffix}'
var storageName = 'st${nameHash}${env}'
var uaiName = 'id-${nameSuffix}'
var cmkStorageName = 'id-cmk-st-${nameSuffix}'
var cmkSearchName = 'id-cmk-search-${nameSuffix}'
var cmkServicebusName = 'id-cmk-sb-${nameSuffix}'

// Built-in role: Key Vault Crypto Service Encryption User
var cryptoServiceEncryptionUserRoleId = 'e147488a-f6f5-4113-8e2d-b22465e65bf6'
var keyOps = [ 'decrypt', 'encrypt', 'sign', 'unwrapKey', 'verify', 'wrapKey' ]

// Public URLs written into App Configuration
var insightBaseUrl = 'https://insight.${workspaceSubdomain}.${routingDomain}'
var cortexAuthBaseUrl = 'https://cortex-auth-ui.${workspaceSubdomain}.${routingDomain}'

// ─── Shared workload identity + federated credentials ─────────────────────────
resource uai 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: uaiName
  location: location
  tags: tags
}

@batchSize(1)
resource federatedCredentials 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2023-01-31' = [
  for sa in workloadServiceAccounts: {
    parent: uai
    name: 'fic-${nameHash}-${sa}'
    properties: {
      issuer: aksOidcIssuerUrl
      subject: 'system:serviceaccount:${tenantNamespace}:${sa}'
      audiences: [ 'api://AzureADTokenExchange' ]
    }
  }
]

// Dedicated CMK identities (Storage / Search / Service Bus double encryption).
resource cmkStorage 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: cmkStorageName
  location: location
  tags: tags
}
resource cmkSearch 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: cmkSearchName
  location: location
  tags: tags
}
resource cmkServicebus 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: cmkServicebusName
  location: location
  tags: tags
}

// ─── Key Vault (module: vault + PE + Secrets User for the workload UAI) ────────
module kv 'modules/keyvault.bicep' = {
  name: 'insight-kv'
  params: {
    name: kvName
    location: location
    tags: tags
    skuName: keyVaultSku
    peSubnetId: peSubnetId
    dnsZoneId: kvDnsZoneId
    workloadPrincipalId: uai.properties.principalId
  }
}

// Existing reference so we can attach control-plane keys + secrets.
resource kvVault 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
  name: kvName
}

// CMK keys (RSA-HSM 4096) — created control-plane, no data-plane wait needed.
resource storageKey 'Microsoft.KeyVault/vaults/keys@2023-07-01' = {
  parent: kvVault
  name: 'storage-key'
  properties: { kty: 'RSA', keySize: 4096, keyOps: keyOps }
  dependsOn: [ kv ]
}
resource searchKey 'Microsoft.KeyVault/vaults/keys@2023-07-01' = {
  parent: kvVault
  name: 'search-key'
  properties: { kty: 'RSA', keySize: 4096, keyOps: keyOps }
  dependsOn: [ kv ]
}
resource servicebusKey 'Microsoft.KeyVault/vaults/keys@2023-07-01' = {
  parent: kvVault
  name: 'servicebus-key'
  properties: { kty: 'RSA', keySize: 4096, keyOps: keyOps }
  dependsOn: [ kv ]
}

// Grant each CMK identity wrap/unwrap on its key.
resource storageKeyRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(storageKey.id, cmkStorage.id, cryptoServiceEncryptionUserRoleId)
  scope: storageKey
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', cryptoServiceEncryptionUserRoleId)
    principalId: cmkStorage.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
resource searchKeyRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(searchKey.id, cmkSearch.id, cryptoServiceEncryptionUserRoleId)
  scope: searchKey
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', cryptoServiceEncryptionUserRoleId)
    principalId: cmkSearch.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
resource servicebusKeyRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(servicebusKey.id, cmkServicebus.id, cryptoServiceEncryptionUserRoleId)
  scope: servicebusKey
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', cryptoServiceEncryptionUserRoleId)
    principalId: cmkServicebus.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// ─── Postgres ─────────────────────────────────────────────────────────────────
module postgres 'modules/postgres.bicep' = {
  name: 'insight-postgres'
  params: {
    name: postgresName
    location: location
    tags: tags
    version: postgresVersion
    skuName: postgresSkuName
    storageMb: postgresStorageMb
    administratorLogin: administratorLogin
    administratorPassword: tenantVault.getSecret('set-${secretSetId}--postgres-password')
    backupRetentionDays: postgresBackupRetentionDays
    geoRedundantBackup: postgresGeoRedundantBackup
    databases: postgresDatabases
    peSubnetId: peSubnetId
    dnsZoneId: postgresDnsZoneId
  }
}

// ─── Key Vault secrets the chart's ExternalSecrets read ──────────────────────
//
// Written by a submodule, because Bicep's getSecret() is only valid as a module
// PARAMETER: it compiles to a reference the platform resolves at deploy time,
// never to a value here, so the connection strings cannot be composed at this
// level. Inside that module the parameters are real values and can be.
module contractSecrets 'modules/contract-secrets.bicep' = {
  name: 'insight-contract-secrets'
  params: {
    keyVaultName: kvName
    postgresFqdn: postgres.outputs.fqdn
    administratorLogin: administratorLogin
    administratorPassword: tenantVault.getSecret('set-${secretSetId}--postgres-password')
    jwtSecretKey: tenantVault.getSecret('set-${secretSetId}--jwt-secret-key')
    spicedbPresharedKey: tenantVault.getSecret('set-${secretSetId}--spicedb-preshared-key')
    llmGatewayMasterKey: tenantVault.getSecret('set-${secretSetId}--llm-gateway-master-key')
  }
  dependsOn: [ kv ]
}

// ─── Redis ────────────────────────────────────────────────────────────────────
module redis 'modules/redis.bicep' = {
  name: 'insight-redis'
  params: {
    name: redisName
    location: location
    tags: tags
    capacity: redisCapacity
    family: redisFamily
    skuName: redisSkuName
    peSubnetId: peSubnetId
    dnsZoneId: redisDnsZoneId
    workloadPrincipalId: uai.properties.principalId
    workloadClientId: uai.properties.clientId
  }
}

// ─── Service Bus (CMK) ────────────────────────────────────────────────────────
module servicebus 'modules/servicebus.bicep' = {
  name: 'insight-servicebus'
  params: {
    name: servicebusName
    location: location
    tags: tags
    capacity: servicebusCapacity
    queues: servicebusQueues
    cmkIdentityId: cmkServicebus.id
    cmkKeyName: 'servicebus-key'
    keyVaultUri: kv.outputs.uri
    peSubnetId: peSubnetId
    dnsZoneId: servicebusDnsZoneId
    workloadPrincipalId: uai.properties.principalId
  }
  dependsOn: [ servicebusKeyRoleAssignment ]
}

// ─── Storage (CMK) ────────────────────────────────────────────────────────────
module storage 'modules/storage.bicep' = {
  name: 'insight-storage'
  params: {
    name: storageName
    location: location
    tags: tags
    sku: storageSku
    containers: storageContainers
    cmkIdentityId: cmkStorage.id
    cmkKeyName: 'storage-key'
    keyVaultUri: kv.outputs.uri
    peSubnetId: peSubnetId
    dnsZoneId: blobDnsZoneId
    workloadPrincipalId: uai.properties.principalId
    lifecycleDeleteAfterDays: storageLifecycleDeleteAfterDays
  }
  dependsOn: [ storageKeyRoleAssignment ]
}

// ─── AI Search (CMK enforcement) ──────────────────────────────────────────────
module search 'modules/search.bicep' = {
  name: 'insight-search'
  params: {
    name: searchName
    location: location
    tags: tags
    sku: searchSku
    replicaCount: searchReplicaCount
    partitionCount: searchPartitionCount
    cmkIdentityId: cmkSearch.id
    peSubnetId: peSubnetId
    dnsZoneId: searchDnsZoneId
    workloadPrincipalId: uai.properties.principalId
  }
  dependsOn: [ searchKeyRoleAssignment ]
}

// ─── Cognitive: Speech (UAI + BYOS), Translator, Document Intelligence ────────
module speech 'modules/cognitive.bicep' = {
  name: 'insight-speech'
  params: {
    name: speechName
    location: location
    tags: tags
    kind: 'SpeechServices'
    skuName: cognitiveServicesSku
    useUserAssignedIdentity: true
    userAssignedIdentityId: uai.id
    userOwnedStorageAccountId: storage.outputs.id
    userOwnedStorageIdentityClientId: uai.properties.clientId
    peSubnetId: peSubnetId
    dnsZoneId: cognitiveDnsZoneId
    dnsZoneGroupName: 'spch-dns-zone-group'
    workloadPrincipalId: uai.properties.principalId
  }
}
module translator 'modules/cognitive.bicep' = {
  name: 'insight-translator'
  params: {
    name: translatorName
    location: location
    tags: tags
    kind: 'TextTranslation'
    skuName: translatorSku
    peSubnetId: peSubnetId
    dnsZoneId: cognitiveDnsZoneId
    dnsZoneGroupName: 'trnsl-dns-zone-group'
    workloadPrincipalId: uai.properties.principalId
  }
}
module documentIntelligence 'modules/cognitive.bicep' = {
  name: 'insight-document-intelligence'
  params: {
    name: documentIntelligenceName
    location: location
    tags: tags
    kind: 'FormRecognizer'
    skuName: cognitiveServicesSku
    peSubnetId: peSubnetId
    dnsZoneId: cognitiveDnsZoneId
    dnsZoneGroupName: 'di-dns-zone-group'
    workloadPrincipalId: uai.properties.principalId
  }
}

// ─── App Configuration keys (non-secret) + feature flags ──────────────────────
var configKeys = [
  { key: 'insight--backend--environment', value: env }
  { key: 'insight--backend--log-level', value: 'INFO' }
  { key: 'insight--backend--bff-api-url', value: 'http://bff:8001' }
  { key: 'insight--backend--ENABLE_TRANSCRIPTION_PERF_EVENTS', value: 'false' }
  { key: 'insight--backend--email-provider', value: 'acs' }
  { key: 'insight--backend--acs-endpoint', value: platformAcsEndpoint }
  { key: 'insight--backend--acs-from-email', value: platformAcsFromEmail }
  { key: 'insight--backend--acs-use-managed-identity', value: 'true' }
  { key: 'insight--bff--backend-api-url', value: 'http://backend:8002' }
  { key: 'insight--bff--api-url', value: 'http://bff:8001' }
  { key: 'insight--bff--agentic-core-url', value: 'http://agentic-core:8003' }
  { key: 'insight--bff--simulator-url', value: 'http://digital-simulator:8010' }
  { key: 'insight--bff--decision-register-url', value: 'http://decision-register:8011' }
  { key: 'insight--bff--cortex-service-url', value: 'http://cortex:8004' }
  { key: 'insight--bff--cortex-base-url', value: insightBaseUrl }
  { key: 'insight--bff--cortex-auth-base-url', value: cortexAuthBaseUrl }
  { key: 'insight--bff--cortex-tenant-id', value: tenantName }
  { key: 'insight--bff--cortex-client-id', value: 'cortex-ui' }
  { key: 'insight--bff--cortex-auth-url', value: cortexAuthBaseUrl }
  { key: 'insight--bff--cortex-token-url', value: '${cortexAuthBaseUrl}/api/auth/token' }
  { key: 'insight--bff--cortex-verify-tls', value: 'true' }
  { key: 'insight--bff--translation-service-url', value: 'http://translation:8012' }
  { key: 'insight--bff--redis-enabled', value: 'true' }
  { key: 'insight--bff--redis-host', value: redis.outputs.hostname }
  { key: 'insight--bff--redis-port', value: '6380' }
  { key: 'insight--bff--redis-use-ssl', value: 'true' }
  { key: 'insight--bff--redis-use-managed-identity', value: 'true' }
  { key: 'insight--bff--azure-redis-username', value: uai.properties.clientId }
  { key: 'insight--cortex--base-url', value: insightBaseUrl }
  { key: 'insight--cortex--auth-base-url', value: cortexAuthBaseUrl }
  { key: 'insight--cortex--tenant-id', value: tenantName }
  { key: 'insight--cortex--client-id', value: 'cortex-ui' }
  { key: 'insight--cortex--redirect-uri', value: '${insightBaseUrl}/auth/callback' }
  { key: 'insight--cortex--verify-tls', value: 'true' }
  { key: 'insight--agentic-core--environment', value: env }
  { key: 'insight--agentic-core--debug', value: 'false' }
  { key: 'insight--agentic-core--log-level', value: 'INFO' }
  { key: 'insight--agentic-core--digital-simulator-url', value: 'http://digital-simulator:8010' }
  { key: 'insight--agentic-core--decision-register-url', value: 'http://decision-register:8011' }
  { key: 'insight--agentic-core--translation-service-url', value: 'http://translation:8012' }
  { key: 'insight--agentic-core--llm-gateway-url', value: 'http://llm-gateway:8005' }
  { key: 'insight--agentic-core--llm-gateway-model-alias', value: 'agentic-chat' }
  { key: 'insight--agentic-core--backend-api-url', value: 'http://backend:8002' }
  { key: 'insight--agentic-core--langfuse-debug', value: 'false' }
  { key: 'insight--agentic-core--azure-speech-region', value: speech.outputs.location }
  { key: 'insight--agentic-core--azure-speech-endpoint', value: speech.outputs.endpoint }
  { key: 'insight--agentic-core--azure-search-endpoint', value: 'https://${search.outputs.name}.search.windows.net' }
  { key: 'insight--agentic-core--azure-search-index-name', value: 'insight-indexer-${tenantName}' }
  { key: 'insight--agentic-core--azure-service-bus-namespace', value: '${servicebus.outputs.name}.servicebus.windows.net' }
  { key: 'insight--agentic-core--indexer-response-queue', value: 'insight-indexer-queue' }
  { key: 'insight--translation--default-target-language', value: 'ar-AE' }
  { key: 'insight--translation--llm-deployment', value: 'translation' }
  { key: 'insight--translation--llm-gateway-url', value: 'http://llm-gateway:8005' }
  { key: 'insight--translation--api-prefix', value: '/api/v1' }
  { key: 'insight--translation--environment', value: env }
  { key: 'insight--translation--log-level', value: 'INFO' }
  { key: 'insight--translation--azure-translator-endpoint', value: translator.outputs.endpoint }
  { key: 'insight--translation--azure-translator-region', value: translator.outputs.location }
  { key: 'insight--digital-simulator--backend-api-url', value: 'http://backend:8002' }
  { key: 'insight--digital-simulator--llm-gateway-url', value: 'http://llm-gateway:8005' }
  { key: 'insight--digital-simulator--decision-register-url', value: 'http://decision-register:8011' }
  { key: 'insight--decision-register--backend-api-url', value: 'http://backend:8002' }
  { key: 'insight--decision-register--llm-gateway-url', value: 'http://llm-gateway:8005' }
  { key: 'insight--decision-register--translation-service-url', value: 'http://translation:8012' }
]

module appconfig 'modules/appconfig.bicep' = {
  name: 'insight-appconfig'
  params: {
    name: appconfigName
    location: location
    tags: tags
    sku: appConfigurationSku
    label: env
    configKeys: configKeys
    featureFlags: loadJsonContent('feature-flags.json')
    peSubnetId: peSubnetId
    dnsZoneId: appConfigurationDnsZoneId
  }
}

// ─── Platform ACS email sender grant (optional, cross-RG) ─────────────────────
module acsEmailGrant 'modules/acs-email-grant.bicep' = if (!empty(platformAcsName) && !empty(platformAcsResourceGroup)) {
  name: 'insight-acs-email-grant'
  scope: resourceGroup(platformAcsResourceGroup)
  params: {
    acsName: platformAcsName
    principalId: uai.properties.principalId
  }
}

// ─── Outputs ──────────────────────────────────────────────────────────────────
@description('Non-secret insight infrastructure values. Maps 1:1 onto the insight chart .Values.appInfra.* keys.')
output appInfra object = {
  environment: env
  tenantName: tenantName
  applicationId: applicationId
  keyvaultTenantId: subscription().tenantId
  workloadIdentityClientId: uai.properties.clientId
  principalId: uai.properties.principalId
  keyvaultUrl: kv.outputs.uri
  appConfigEndpoint: appconfig.outputs.endpoint
  postgresHost: postgres.outputs.fqdn
  postgresDatabases: 'insight,spicedb'
  redisHost: redis.outputs.hostname
  serviceBusNamespace: servicebus.outputs.name
  serviceBusFqdn: '${servicebus.outputs.name}.servicebus.windows.net'
  serviceBusQueues: 'insight-indexer-queue,meeting-queue'
  indexerResponseQueue: 'insight-indexer-queue'
  aiSearchEndpoint: 'https://${search.outputs.name}.search.windows.net'
  storageAccountName: storage.outputs.name
  storageBlobEndpoint: storage.outputs.primaryBlobEndpoint
  storageContainers: 'insight-audio-brief,insight-user-documents'
  storagePathPrefixes: 'indexer-queue'
  speechEndpoint: speech.outputs.endpoint
  speechRegion: speech.outputs.location
  translatorEndpoint: translator.outputs.endpoint
  translatorRegion: translator.outputs.location
  documentIntelligenceEndpoint: documentIntelligence.outputs.endpoint
  spiceDbEndpoint: 'spicedb:50051'
  acsEndpoint: platformAcsEndpoint
  acsFromEmail: platformAcsFromEmail
  // Folded in so a single `appInfra -> appInfra` wire (the platform overwrites
  // the whole subtree) still turns on the Key Vault ExternalSecrets path.
  externalSecrets: {
    enabled: true
    serviceAccountName: 'backend-sa'
    secretStoreName: 'insight-app-infra'
  }
}

@description('Object ID of the shared workload identity (for cross-app role assignments).')
output principalId string = uai.properties.principalId
@description('Resource ID of the storage account (cross-app RBAC scope).')
output storageAccountId string = storage.outputs.id
@description('Resource ID of the insight-indexer-queue (cross-app RBAC scope).')
output indexerResponseQueueId string = servicebus.outputs.indexerQueueId
@description('Name of the insight V2 indexer response queue.')
output indexerResponseQueueName string = 'insight-indexer-queue'
